{% set name = "wagtail" %}
{% set version = "6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtail-{{ version }}.tar.gz
  sha256: 3e311f367867741a2a025ae1c6d498c177ae1936a4b92444177804fa713edff0

build:
  entry_points:
    - wagtail = wagtail.bin.wagtail:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=4.2,<6.0
    - django-modelcluster >=6.2.1,<7.0
    - django-permissionedforms >=0.1,<1.0
    - django-taggit >=5.0,<6.2
    - django-treebeard >=4.5.1,<5.0
    - djangorestframework >=3.15.1,<4.0
    - django-filter >=23.3,<25
    - django-tasks >=0.6.1,<0.7
    - draftjs_exporter >=2.1.5,<6.0
    - pillow >=9.1.0,<12.0.0
    - beautifulsoup4 >=4.8,<4.13
    - willow >=1.8.0,<2
    - requests >=2.11.1,<3.0
    - openpyxl >=3.0.10,<4.0
    - anyascii >=0.1.5
    - telepath >=0.3.1,<1
    - laces >=0.1,<0.2

test:
  imports:
    - wagtail
  commands:
    - pip check
    - wagtail help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://wagtail.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A Django content management system focused on flexibility and user experience '
  description: |
    Wagtail is an open source content management system built on Django, with a strong community and commercial support.
    It's focused on user experience, and offers precise control for designers and developers.
  doc_url: https://docs.wagtail.org/en/stable/
  dev_url: https://github.com/wagtail/wagtail

extra:
  recipe-maintainers:
    - darynwhite
    - rxm7706
