{% set name = "wagtail" %}
{% set version = "6.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtail-{{ version }}.tar.gz
  sha256: cec3e6d4920a6d178fa1eb6f4af80b370fdd5570ed924b979104e157f10ca097

build:
  entry_points:
    - wagtail = wagtail.bin.wagtail:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=4.2,<6.0
    - django-modelcluster <7.0,>=6.2.1
    - django-permissionedforms <1.0,>=0.1
    - django-taggit >=5.0,<7
    - django-treebeard <5.0,>=4.5.1
    - djangorestframework <4.0,>=3.15.1
    - django-filter >=23.3
    - django-tasks <0.7,>=0.6.1
    - draftjs_exporter <6.0,>=2.1.5
    - pillow >=9.1.0,<12.0.0
    - beautifulsoup4 >=4.8,<5
    - willow >=1.8.0,<2
    - requests <3.0,>=2.11.1
    - openpyxl <4.0,>=3.0.10
    - anyascii >=0.1.5
    - telepath <1,>=0.3.1
    - laces <0.2,>=0.1
    # - tblib <3.0,>=2.0
    # - sphinxcontrib-spelling <8,>=7
    # - sphinx-wagtail-theme ==6.5.0
    # - sphinx-autobuild >=0.6.0
    # - semgrep ==1.40.0
    # - ruff ==0.1.5
    # - python-dateutil >=2.7
    # - pyenchant <4,>=3.1.1
    # - polib <2.0,>=1.1
    # - myst-parser ==2.0.0
    # - freezegun >=0.3.8
    # - factory_boy >=3.2
    # - doc8 ==0.8.1
    # - djhtml ==3.0.6
    # - django-pattern-library >=0.7
    # - curlylint ==0.13.1
    # - coverage >=3.7.0
    # - boto3 <2,>=1.28
    # - azure-mgmt-frontdoor <1.1,>=1.0
    # - azure-mgmt-cdn <13.0,>=12.0
    # - Willow <2,>=1.8.0
    # - Sphinx >=7.3
    # - Pillow <12.0.0,>=9.1.0
    # - Jinja2 <3.2,>=3.0
    # - Django <6.0,>=4.2

test:
  imports:
    - wagtail
  commands:
    - pip check
    - wagtail help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://wagtail.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A Django content management system focused on flexibility and user experience '
  description: |
    Wagtail is an open source content management system built on Django, with a strong community and commercial support.
    It's focused on user experience, and offers precise control for designers and developers.
  doc_url: https://docs.wagtail.org/en/stable/
  dev_url: https://github.com/wagtail/wagtail

extra:
  recipe-maintainers:
    - darynwhite
    - rxm7706
